<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Exports the strings needed by the installer
 *
 * Moodle core contains a subset of strings needed for the start of the installation.
 * The list of required strings is maintained in install/stringnames.txt. This
 * script parses that file and exports the translations into a configured destination.
 *
 * @package   local_amos
 * @copyright 2010 David Mudrak <david.mudrak@gmail.com>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once(dirname(dirname(dirname(dirname(__FILE__)))) . '/config.php');
require_once($CFG->dirroot . '/local/amos/cli/config.php');
require_once($CFG->dirroot . '/local/amos/mlanglib.php');

if (! $strings = file($CFG->dirroot . '/install/stringnames.txt', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES)) {
    echo "Unable to read stringnames.txt\n";
    exit(1);
}
$list = array();    // [component][stringid] => null
foreach ($strings as $string) {
    list($stringid, $component) = array_map('trim', explode(',', $string));
    if (!isset($list[$component])) {
        $list[$component] = array();
    }
    if (!isset($list[$component][$stringid])) {
        $list[$component][$stringid] = null;
    }
}
unset($strings);

if (empty($list)) {
    echo "ERROR Unable to get the list of strings to export\n";
    exit(1);
}
$tree = mlang_tools::components_tree(array('branch' => mlang_version::MOODLE_20));
$langs = array_keys($tree[mlang_version::MOODLE_20]);
unset($tree);
$version = mlang_version::by_code(mlang_version::MOODLE_20);
remove_dir(AMOS_EXPORT_INSTALLER_DIR, true);

$phpdoc = <<<EOF
/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/en/Development:Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */


EOF;

foreach ($list as $componentname => $stringids) {
    foreach ($langs as $lang) {
        $component = mlang_component::from_snapshot($componentname, $lang, $version, null, false, false, array_keys($stringids));
        if ($component->has_string()) {
            $file = AMOS_EXPORT_INSTALLER_DIR . '/' . $version->dir . '/install/lang/' . $lang . '/' . $component->name . '.php';
            if (!file_exists(dirname($file))) {
                mkdir(dirname($file), 0772, true);
            }
            echo "$file\n";
            $component->export_phpfile($file, $phpdoc);
        }
        $component->clear();
    }
}
echo "DONE\n";
