#!/bin/bash -e

# Fix drift between moodle.git and AMOS
# Sometimes, the English string changes are not parsed correctly (due to non-linearity of Git commits).
# This job checks for differences between the Git and AMOS repositories.
# On detected drift, the status is set to UNSTABLE and e-mail is sent. The drift is then automatically
# fixed so the next execution shoudl be stable again.
# upstream: en-track
# downstream: en-revclean

php $AMOSCLIROOT/fix-drift.php --execute
