#!/bin/bash -e

# Update language packs used at lang.moodle.org
# Once they are available, use the newly generated language packs at 
# http://lang.moodle.org itself.
# upstream: zip-packs-commit

cd $CFGDATAROOT/lang/
git pull
cd $CFGDIRROOT
php admin/cli/purge_caches.php
